################################
#A one-touch scene controller  #
################################

name: Bedroom 2 dim
entities:
  light.fibaro_system_fgd212_dimmer_2_level_2_0:
    state: on
    transition: 2
    brightness: 35