#####################################
#Creates a pin on a map for Laura's #
#location in the form of camera feed#
#####################################

name: Laura
platform: generic
still_image_url: !secret tracker_cam_laura
limit_refetch_to_url_change: true