###############################
#Switches the light off in the#
#boys room after 30 minutes   #
###############################

alias: 'Boys room light auto-off'
trigger:
  platform: state
  entity_id: light.fibaro_system_fgd212_dimmer_2_level_2_0
  to: 'on'
  for:
    minutes: 30
action:
  service: homeassistant.turn_off
  entity_id: light.fibaro_system_fgd212_dimmer_2_level_2_0