###################################
#Obtains information from various #
#services and presents them as    #
#sensor readings                  #
###################################

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: !secret sensor_ssl_command

- platform: version
  name: Installed HA version

- platform: rest
  resource: https://pypi.python.org/pypi/homeassistant/json
  name: HA upstream
  value_template: '{{ value_json.info.version }}'
  scan_interval: 3600

- platform: haveibeenpwned
  email: !secret haveibeenpwned_email

- platform: hue

- platform: travisci
  api_key: !secret sensor_travisci
  