- platform: template
  sensors:

    calendar:
      value_template: >
        {{ strptime(states.calendar.marcforthrungmailcom.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A %B %d at %H:%M") }}:
        {{ states.calendar.marcforthrungmailcom.attributes.message }}
      friendly_name: 'Next Event'
      
    dark_outside:
        friendly_name: 'Dark outside'
        value_template: >
          {% if (states.sun.sun.attributes.elevation | int < 3) %}true
          {% elif ( (states.sun.sun.attributes.elevation | int < 4) and (states.sensor.dark_sky_cloud_coverage.state | int > 50)) %}true
          {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 90) %}true
          {% else %}false
          {% endif %}