###################################
#Obtains travel time information  #
#and presents it as sensor reading#
###################################

- platform: google_travel_time
  name: Marc to home
  api_key: !secret google_map_api_key
  origin: device_tracker.marc_pixel
  destination: zone.home
  options:
    units: imperial

- platform: google_travel_time
  name: Marc to Laura
  api_key: !secret google_map_api_key
  origin: device_tracker.marc_pixel
  destination: device_tracker.laura_iphone
  options:
    units: imperial
    
- platform: google_travel_time
  name: Marc to kids house
  api_key: !secret google_map_api_key
  origin: device_tracker.marc_pixel
  destination: zone.marcs_kids_house
  options:
    units: imperial

- platform: google_travel_time
  name: Laura to Courtney
  api_key: !secret google_map_api_key
  origin: device_tracker.laura_iphone
  destination: device_tracker.courtney_iphone
  options:
    units: imperial