#########################################
#The main configuration.yaml - see my   #
#README.md for information on how I have#
#structured and organised this file     #
#and the !include files that it links to#
#########################################

#Core program
homeassistant: !include config/core/homeassistant.yaml

#Web interface UX and security
frontend:
config:
group: !include_dir_merge_named config/group/
http: !include config/misc/http.yaml
updater:
recorder: !include config/misc/recorder.yaml
logbook: !include config/misc/logbook.yaml

#My components
zwave:
  usb_path: /dev/ttyAMA0
light: !include config/misc/light.yaml
emulated_hue: !include config/misc/emulated_hue.yaml
device_tracker: !include config/misc/device_tracker.yaml
device_sun_light_trigger: !include config/misc/device_sun_light_trigger.yaml
mqtt: !include config/misc/mqtt.yaml  
zone: !include_dir_list config/zone/
media_player: !include config/misc/media_player.yaml
tts:
  - platform: google
notify: !include config/misc/notify.yaml
hdmi_cec: !include config/misc/hdmi_cec.yaml
camera: !include_dir_list config/camera/
google: !include config/misc/google.yaml
ifttt:
  key: !secret ifttt_api_key  
sun:
sensor: !include_dir_merge_list config/sensor/
weblink: !include config/misc/weblink.yaml

#My automations/scripts/scenes/etc
automation: !include_dir_list config/automation/
script: !include_dir_merge_named config/script/
scene: !include_dir_list config/scene/
input_boolean: !include config/misc/input_boolean.yaml
input_select: !include config/misc/input_select.yaml
alarm_control_panel: !include config/misc/alarm_control_panel.yaml
alert: !include_dir_merge_named config/alert