#########################################
#The main configuration.yaml - see my   #
#README.md for information on how I have#
#structured and organised this file     #
#and the !include files that it links to#
#########################################

##################
## Core program ##
##################

homeassistant: !include config/core/homeassistant.yaml

###################################
## Web interface UX and security ##
###################################

frontend:
group: !include_dir_merge_named config/group/
http: !include config/misc/http.yaml
recorder:
  purge_days: 14
  db_url: !secret recorder_db_url
logbook: !include config/misc/logbook.yaml

#######################################
## My components/devices/sensors/etc ##
#######################################

zwave:
  usb_path: /dev/ttyAMA0
light:
  platform: hue
  host: !secret hue_light_host
emulated_hue: !include config/misc/emulated_hue.yaml
device_tracker:
  - platform: owntracks
mqtt: !include config/misc/mqtt.yaml  
zone: !include_dir_list config/zone/
media_player: !include config/misc/media_player.yaml
tts:
  - platform: google
notify: !include config/misc/notify.yaml
#hdmi_cec: !include config/misc/hdmi_cec.yaml
camera: !include_dir_list config/camera/
#android_ip_webcam: !include config/misc/android_ip_webcam.yaml
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret
ifttt:
  key: !secret ifttt_api_key  
sun:
sensor: !include_dir_merge_list config/sensor/
weblink: !include config/misc/weblink.yaml
updater:

#######################################
## My automations/scripts/scenes/etc ##
#######################################

automation old: !include_dir_list config/automation/
device_sun_light_trigger: !include config/misc/device_sun_light_trigger.yaml
script: !include_dir_merge_named config/script/
scene: !include_dir_list config/scene/
input_boolean: !include config/misc/input_boolean.yaml
input_select: !include config/misc/input_select.yaml
alarm_control_panel: !include config/misc/alarm_control_panel.yaml
shell_command: !include config/misc/shell_command.yaml