#########################################
#The main configuration.yaml - see my   #
#README.md for information on how I have#
#structured and organised this file     #
#and the !include files that it links to#
#########################################

##################
## Core program ##
##################

homeassistant: !include config/core/homeassistant.yaml

###################################
## Web interface UX and security ##
###################################

frontend:
  themes: !include_dir_merge_named config/themes/
config:
map:
group: !include_dir_merge_named config/group/
http: !include config/misc/http.yaml
recorder:
  purge_interval: 7
  purge_keep_days: 14
logbook: !include config/misc/logbook.yaml

#######################################
## My components/devices/sensors/etc ##
#######################################

#zwave:
#  usb_path: /dev/ttyAMA0
light:
  platform: hue
  host: !secret hue_light_host
emulated_hue: !include config/misc/emulated_hue.yaml
device_tracker:
  - platform: owntracks
mqtt: !include config/misc/mqtt.yaml  
zone: !include_dir_list config/zone/
media_player: !include config/misc/media_player.yaml
tts:
  - platform: google
    cache: false
telegram_bot: !include config/misc/telegram_bot.yaml
notify: !include config/misc/notify.yaml
camera: !include_dir_list config/camera/
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret
sun:
sensor: !include_dir_merge_list config/sensor/
weblink: !include config/misc/weblink.yaml
updater:
  include_used_components: true

#######################################
## My automations/scripts/scenes/etc ##
#######################################

automation: !include_dir_list config/automation/
script: !include_dir_merge_named config/script/
scene: !include_dir_list config/scene/
input_boolean: !include config/misc/input_boolean.yaml
input_select: !include config/misc/input_select.yaml
shell_command: !include config/misc/shell_command.yaml