##################################################
##################################################
######The system created this file when the ######
######'config:' component was introduced,   ######
######and I haven't quite figured out if I  ######
######actually need this or not yet, as I   ######
######did not have a z-wave config file in  ######
######the first place, and everything is    ######
######working as it should.  I also don't   ######
######know if it will cause problems if I do######
######delete it, so here it is, left blank! ######
##################################################
##################################################