#################################
#Placing entities on the card   #
#################################

bedroom_two_lights:
  name: Lights
  control: hidden
  entities:
    - light.fibaro_system_fgd212_dimmer_2_level_2_0
    - input_select.bedroom_two_scenes