#################################
#Placing entities on the card   #
#################################

home_entertainment:
  name: Home Entertainment
  control: hidden
  entities:
    - switch.hdmi_5
    - script.surround_volume_up
    - script.mute_surround
    - script.surround_volume_down