#################################
#Placing entities on the card   #
#################################

home_entertainment:
  name: Home Entertainment
  entities:
    - switch.hdmi_0
    - switch.hdmi_2
    - switch.hdmi_4
    - switch.hdmi_5
    - script.surround_volume_up
    - script.mute_surround
    - script.surround_volume_down