#################################
#Placing entities on the card   #
#################################

master_bedroom_lights:
  name: Lights
  entities:
    - light.bedroom_ceiling
    - light.bedside_1
    - light.bedside_2
    - input_select.master_bedroom_scenes

bedroom_two_lights:
  name: Lights
  control: hidden
  entities:
    - light.boys_room_zwave_dimmer_level
    - input_select.bedroom_two_scenes

livingroom_lights:
  name: Lights
  control: hidden
  entities:
    - light.living_room_zwave_dimmer_level
    - input_select.living_room_scenes