#################################
#Placing entities on the card   #
#################################

master_bedroom_lights:
  name: Lights
  entities:
    - light.bedroom_ceiling
    - light.bedside_1
    - light.bedside_2
    - input_select.master_bedroom_scenes

bedroom_two_lights:
  name: Lights
  control: hidden
  entities:
    - light.fibaro_system_fgd212_dimmer_2_level_2_0
    - input_select.bedroom_two_scenes

livingroom_lights:
  name: Lights
  control: hidden
  entities:
    - light.fibaro_system_fgd212_dimmer_2_level_3_0
    - input_select.living_room_scenes