#################################
#Placing entities on the card   #
#################################

livingroom_lights:
  name: Lights
  entities:
    - light.fibaro_system_fgd212_dimmer_2_level_11_0
    - scene.livingroom_dim
    - scene.livingroom_normal
    - scene.livingroom_bright
    - scene.livingroom_full