#################################
#Placing entities on the card   #
#################################

livingroom_lights:
  name: Lights
  control: hidden
  entities:
    - light.fibaro_system_fgd212_dimmer_2_level_3_0
    - input_select.living_room_scenes