#################################
#Placing entities on the card   #
#################################

master_bedroom_lights:
  name: Lights
  entities:
    - light.bedroom_ceiling
    - light.bedside_1
    - light.bedside_2
    - input_select.master_bedroom_scenes