#################################
#Placing entities on the card   #
#################################

master_bedroom_lights:
  name: Lights
  entities:
    - light.bedroom_ceiling
    - light.bedside_1
    - light.bedside_2
    - script.master_bedroom_arctic_aurora
    - script.master_bedroom_bright
    - script.master_bedroom_concentrate
    - script.master_bedroom_dimmed
    - script.master_bedroom_energize
    - script.master_bedroom_nightlight
    - script.master_bedroom_read
    - script.master_bedroom_relax
    - script.master_bedroom_savanna_sunset
    - script.master_bedroom_spring_blossom
    - script.master_bedroom_tropical_twilight