#################################
#Placing entities on the card   #
#################################

Tracker:
  - device_tracker.marcs_phone_marcs_pixel_phone
  - device_tracker.lauras_phone_lauras_phone