#################################
#Placing entities on the card   #
#################################

Zwave:
  - zwave.fibaro_system_fgd212_dimmer_2_2
  - zwave.fibaro_system_fgd212_dimmer_2_3
  - zwave.zwaveme_razberry_controller_2016_zwave_1