################################
#Setting up the device trackers#
#for presence detection        #
################################

- platform: owntracks_http
  max_gps_accuracy: 250
  track_new_devices: false

- platform: bluetooth_tracker