################################
#Setting up the device trackers#
#for presence detection        #
################################

- platform: owntracks
  max_gps_accuracy: 250

#- platform: bluetooth_tracker