#####################################
#Configuration information for the  #
#telegram bot used for notifications#
#####################################

- platform: webhooks
  api_key: !secret telegram_bot_api_key_marc
  parse_mode: html
  allowed_chat_ids:
    - !secret telegram_bot_chat_id_marc

- platform: webhooks
  api_key: !secret telegram_bot_api_key_laura
  parse_mode: html
  allowed_chat_ids:
    - !secret telegram_bot_chat_id_laura

#- platform: webhooks
#  api_key: !secret telegram_bot_api_key
#  parse_mode: html
#  allowed_chat_ids:
#    - !secret telegram_bot_chat_id_courtney