##############################################
#Switches the landing lights to a night light#
##############################################

alias: 'Landing night light off'
initial_state: 'on'
trigger:
  platform: state
  event: sensor.dark_outside
  to: 'false'
action:
  service: light.turn_off
  entity_id: light.landing