##############################################
#Switches the landing lights to a night light#
##############################################

alias: 'Landing night light off'
initial_state: 'on'
trigger:
  platform: sun
  event: sunrise
  offset: '+00:40:00'
action:
  service: light.turn_off
  entity_id: light.landing