#############################
#Setting Maintenance Mode to#
#'off' turns red theme off  #
#############################

alias: 'Maintenance mode off'
trigger:
  platform: state
  entity_id: input_boolean.maintenance_mode
  to: 'off'
action:
  service: frontend.set_theme
  data:
    name: default