################################
#A one-touch scene controller  #
################################

name: Bedroom 2 dim
entities:
  light.boys_room_zwave_dimmer_level:
    state: on
    transition: 2
    brightness: 35