##################################
#Creating one presence entity for#
#Laura based on a combination of #
#nmap and owntracks data         #
##################################

Laura_Tracker:
  name: Laura
  entities:
    - device_tracker.24f09473a321
    - device_tracker.lauras_phone_lauras_phone