###################################
#Obtains host system information  #
#and presents it as sensor reading#
###################################

- platform: cpuspeed

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
    

- platform: speedtest
  minute: 17
  hour:
    - 0
    - 4
    - 8
    - 12
    - 16
    - 20
  monitored_conditions:
    - ping
    - download
    - upload
    
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: !secret sensor_ssl_command

- platform: command_line
  name: Current HA version
  command: "/srv/hass/hass_venv/bin/hass --version"
  scan_interval: 86400

- platform: haveibeenpwned
  email: !secret haveibeenpwned_email