###################################
#Obtains host system information  #
#and presents it as sensor reading#
###################################

- platform: cpuspeed

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: since_last_boot