########################
#Element of the package#
########################

- platform: template
  sensors:
    all_alarm_clock_hour:
      value_template: '{{ states.input_number.all_alarm_clock_hour.state | int }}'
    all_alarm_clock_minute:
      value_template: '{{ states.input_number.all_alarm_clock_minute.state | int }}'
    all_alarm_clock_time:
      value_template: >-
        {{ states.sensor.all_alarm_clock_hour.state }}:
        {%- if states.sensor.all_alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.all_alarm_clock_minute.state }}