########################
#Element of the package#
########################

all_alarm_clock_hour:
  name: Hour
  icon: mdi:timer
  initial: 6
  min: 0
  max: 23
  step: 1

all_alarm_clock_minute:
  name: Minute
  icon: mdi:timer
  initial: 15
  min: 0
  max: 55
  step: 5