########################
#Element of the package#
########################

all_alarm_clock:
  control: hidden
  name: 'MASTER Alarm Clock - TESTING!'
  entities:
    - input_slider.all_alarm_clock_hour
    - input_slider.all_alarm_clock_minute
    - script.all_sync