##################################
#Notifies me if the havibeenpwned#
#sensor activates for any of my  #
#email addresses if breached     #
##################################

alias: 'Breach email haveibeenpwned violet'
trigger:
  platform: numeric_state
  entity_id: !secret sensor_email_violet
  above: 0
action:
  service: notify.pushbullet_marc
  data:
    message: 'Warning - HaveIbeenPwned detected a breach on Violet email address'