##################################
#Notifies me if the havibeenpwned#
#sensor activates for any of my  #
#email addresses if breached     #
##################################

alias: 'Breach email haveibeenpwned hass'
trigger:
  platform: numeric_state
  entity_id: !secret sensor_email_hass
  above: 1
action:
  service: notify.pushbullet_marc
  data:
    message: 'Warning - HaveIbeenPwned detected a breach on your HA email address'