#################################
#Notifies me via pushbullet when#
#the SSL certificate is expiring#
#################################

alias: 'SSL expiry notification'
trigger:
  platform: numeric_state
  entity_id: sensor.ssl_cert_expiry
  below: 21
action:
  service: notify.telegram_marc
  data:
    message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'