#################################
#Runs the certbot autorenew when#
#the SSL certificate is expiring#
#################################

alias: 'Auto renew SSL cert'
trigger:
  platform: numeric_state
  entity_id: sensor.ssl_cert_expiry
  below: 29
action:
  service: shell_command.renew_ssl