###############################
#This automation replies to a #
#telegram message with various#
#status details for the system#
###############################

alias: 'Telegram reply with Status'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/status'
action:
  - service: notify.telegram_marc
    data_template:
      message: " System is online!
      
      
      It's been {{states.sensor.since_last_boot.state}} since last boot, and there are {{states.sensor.ssl_cert_expiry.state}} days left on the SSL certificate.
      
      
      Currently the tracker group is {{states.group.all_devices.state}}.
      
      Living room lights are {{states.group.livingroom_lights.state}}.
      
      Boys room lights are {{states.group.bedroom_two_lights.state}}.
      
      Master bedroom lights are {{states.group.master_bedroom_lights.state}}.
      
      
      The weather at home is currently {{states.sensor.dark_sky_hourly_summary.state}}"