##################################
#Hidden entities, setting icons  #
##################################

device_tracker.phone_marcs_pixel_phone:
  hidden: true
  
sensor.marc_to_home:
  icon: mdi:car

sensor.marc_to_laura:
  icon: mdi:car

sensor.marc_to_kids_house:
  icon: mdi:car
  
group.marc_tracker:
  friendly_name: Marc
  entity_picture: /local/marc.jpg
  
group.laura_tracker:
  friendly_name: Laura
  entity_picture: /local/laura.jpg