######################################
#Runs a bash script that syncs the   #
#.homeassistant directory to dropbox #
######################################

sync_dropbox:
  alias: Sync Dropbox
  sequence:
    - service: shell_command.sync_dropbox