####################################
#A Radio player for the chromecasts#
####################################
  
input_select: !include chromecast_radio/chromecast_input_select.yaml
input_slider: !include chromecast_radio/chromecast_input_slider.yaml
group: !include chromecast_radio/chromecast_group.yaml
script: !include chromecast_radio/chromecast_script.yaml
automation: !include chromecast_radio/chromecast_automation.yaml
homeassistant:
  customize: !include chromecast_radio/chromecast_customize.yaml