#####################################
#An alarm clock feature that flashes#
#lights around the house but not in #
#kids roooms after their bedtime!   #
#####################################

input_slider: !include timer/timer_input_slider.yaml
sensor: !include timer/timer_sensor.yaml
script: !include timer/timer_script.yaml
automation: !include timer/timer_automation.yaml
group: !include timer/timer_group.yaml
homeassistant:
  customize: !include timer/timer_customize.yaml