##################################
#Notifies me if the motion sensor#
#activates on Android IP web cam #
##################################

alias: 'IP webcam motion sensor'
trigger:
  platform: state
  entity_id: binary_sensor.living_room_android_motion_active
  to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: 'group.all_devices'
      state: 'not_home'
    - condition: state
      entity_id: 'input_boolean.kids_night_mode'
      state: 'on'
action:
  service: notify.telegram_marc
  data:
    message: 'Motion detected in living room'
    data:
      photo:
       - url: !secret android_cam_photo_url
         username: !secret android_cam_username
         password: !secret android_cam_password
         caption: 'IP Webcam - Motion detected in living room'