###test#####

alias: 'Telegram bot reaction to event'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/lightsoff'
action:
  - service: homeassistant.turn_off
    entity_id: light.living_room_zwave_dimmer_level
  - service: notify.telegram_marc
    data:
      message: 'Lights turned off!'