#################################
#Placing cards/entites on a tab #
#################################

kitchen:
  view: yes
  name: Kitchen
  icon: mdi:silverware-variant
  entities:
    - media_player.kitchen_cca