#################################
#Placing cards/entites on a tab #
#################################

Livingroom:
  view: yes
  name: Living Room
  icon: mdi:sofa
  entities:
    - group.livingroom_lights
    - media_player.living_room_kodi
    - group.living_alarm_clock
    - camera.living_room_android