#################################
#Placing cards/entites on a tab #
#################################

Livingroom:
  view: yes
  name: Living Room
  entities:
    - group.livingroom_lights
    - group.home_entertainment
    - media_player.living_room_kodi
    - media_player.hdmi_4