#################################
#Placing cards/entites on a tab #
#################################

location:
  view: yes
  name: Location
  icon: mdi:google-maps
  entities:
    - group.phone_trackers
    - camera.marc
    - camera.laura
    - group.travel_time