#################################
#Placing cards/entites on a tab #
#################################

location:
  view: yes
  name: Location
  entities:
    - group.tracker
    - camera.marc
    - camera.laura
    - group.travel_time