###########################################
#Switches the living room/landing lights  #
#on when it is sunset and somebody is home#
###########################################

alias: 'Lights on when dark - already home'
initial_state: 'on'
trigger:
  platform: sun
  event: sunset
  offset: "-00:40:00"
condition:
  condition: state
  entity_id: sensor.home_status
  state: 'Occupied'
action:
  - service: scene.turn_on
    entity_id: scene.livingroom_sunset
  - service: script.landing_light_scene