######################################
#Switches the lights off if they came#
#on sue to the overcast sensor, and  #
#the clouds pass                     #
######################################

alias: 'Overcast Lights Off'
trigger:
  platform: state
  entity_id: binary_sensor.overcast
  to: 'off'
  for:
    minutes: 11
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunrise
      before: sunset
    - condition: state
      entity_id: light.living_room_zwave_dimmer_level
      state: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: light.living_room_zwave_dimmer_level