#####################
#Zone for Kids house#
#####################

name: Marc's Kids House
latitude: !secret marcs_kids_house_latitude
longitude: !secret marcs_kids_house_longitude
radius: 250
icon: mdi:home