#################################
#Placing cards/entites on a tab #
#################################

girls_room:
  view: yes
  name: Girls Room
  icon: mdi:human-female
  entities:
    - group.bedroom_two_lights
    - group.boys_alarm_clock