#################################
#Placing cards/entites on a tab #
#################################

kitchen:
  view: yes
  name: Kitchen
  icon: mdi:silverware-variant
  entities:
    - media_player.kitchencca
    - media_player.downstairs_group
    - group.downstairs_alarm_clock