#################################
#Placing cards/entites on a tab #
#################################

Livingroom:
  view: yes
  name: Living Room
  icon: mdi:sofa
  entities:
    - group.livingroom_lights
    - media_player.living_room_kodi
    - media_player.livingroomcca
    - media_player.downstairs_group
    - group.downstairs_alarm_clock