#####################
#This is just a test#
######################

flash_light_test:
  alias: Flash On
  sequence:
    - alias: clear lights
      service: homeassistant.turn_off
      data:
        entity_id: group.master_bedroom_lights
    - alias: First light On
      service: homeassistant.turn_on
      data:
        entity_id: light.bedroom_ceiling
        effect: random
        brightness: 255
    - delay:
        seconds: 2        
    - alias: Second light On
      service: homeassistant.turn_on
      data:
        entity_id: light.bedside_1
        effect: random
        brightness: 255
    - delay:
        seconds: 2
    - alias: First light Off
      service: homeassistant.turn_off
      data:
        entity_id: light.bedroom_ceiling
    - delay:
        seconds: 2
    - alias: Third light On
      service: homeassistant.turn_on
      data:
        entity_id: light.bedside_2
        effect: random
        brightness: 255
    - delay:
        seconds: 2
    - alias: Second light Off
      service: homeassistant.turn_off
      data:
        entity_id: light.bedside_1
    - delay:
        seconds: 2            
    - alias: loop
      service: script.turn_on
      data:
        entity_id: script.flash_light_test