################################
#Flash the lights in the house #
#in sequence, like an alarm    #
################################

alarm_light_flash:
  alias: Alarm Light Flash
  sequence:
    - service: homeassistant.turn_off
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_2_0
      
    - service: homeassistant.turn_on
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3_0
      data:
        brightness: 255
        
    - delay:
        seconds: 3
        
    - service: homeassistant.turn_off
      entity_id: light.master_bedroom
      
    - service: homeassistant.turn_on
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_2_0
      data:
        brightness: 255
        
    - delay:
        seconds: 3
        
    - service: homeassistant.turn_off
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3_0
      
    - service: homeassistant.turn_on
      entity_id: light.master_bedroom
      data:
        effect: random
        brightness: 255
        
    - service: script.turn_on
      entity_id: script.alarm_light_flash_loop