###############
#Looper script#
###############

alarm_light_flash_loop:
  alias: Alarm Light Flash Loop
  sequence:
    - delay:
        seconds: 3
      
    - service: script.turn_on
      entity_id: script.alarm_light_flash