####################################
#Linking to google calendar via API#
####################################

client_id: !secret google_calendar_client_id
client_secret: !secret google_calendar_secret