#####################################
#Maps HDMI device so scripts can    #
#control them as part of automations#
#####################################

devices:
  TV: 0.0.0.0
  Kodi: 3.1.0.0
  BluRay: 3.2.0.0
  Surround: 3.0.0.0