###################################
#Customize multiple things at once#
###################################

"sensor.breaches*":
  icon: mdi:email-secure

"sensor.*clock_hour*":
  hidden: true

"sensor.*clock_minute*":
  hidden: true

"sensor.*clock_time_long*":
  hidden: true

"sensor.*zwave*":
  hidden: true

"light.*2*":
  hidden: true

"sensor.marc_to*":
  icon: mdi:car

"weblink.*":
  icon: mdi:web

"zwave.*":
  icon: mdi:signal-variant

"sensor.*android*":
  hidden: true