#####################################
#Core settings for the HASS instance#
#####################################

name: Home
latitude: !secret latitude
longitude: !secret longitude
elevation: !secret elevation
time_zone: !secret time_zone
unit_system: metric
customize: !include_dir_merge_named ../customize/