########################################
#This connects to my android tablet and#
#uses the onboard camera as an IP cam  #
########################################

- host: !secret android_cam_host
  port: !secret android_cam_port
  name: Living Room Android
  username: !secret android_cam_username
  password: !secret android_cam_password
  motion_sensor: true