#####################################
#Maps HDMI device so scripts can    #
#control them as part of automations#
#####################################

devices:
  BluRay: 3.2.0.0
  Surround: 3.0.0.0

types:
  hdmi_cec.hdmi_4: switch
  hdmi_cec.hdmi_5: switch