#######################################
#Action buttons to set modes on the UX#
#######################################

guest_mode:
  name: Guest mode
  initial: off
  icon: mdi:human-handsup

holiday_mode:
  name: Holiday mode
  initial: off
  icon: mdi:airplane

school_day_mode:
  name: School Day mode
  initial: off
  icon: mdi:school

bathtime_mode:
  name: Bathtime mode
  initial: off
  icon: mdi:basket-fill

cycling_mode:
  name: Cycling to work mode
  initial: off
  icon: mdi:bike

away_mode:
  name: Away mode
  initial: off
  icon: mdi:alert-circle-outline

kids_night_mode:
  name: Kids night monitor
  initial: off
  icon: mdi:human-child