#######################################
#Action buttons to set modes on the UX#
#######################################

guest_mode:
  name: Guest mode
  initial: off
  icon: mdi:car
  
holiday_mode:
  name: Holiday mode
  initial: off
  icon: mdi:flash

school_day_mode:
  name: School Day mode
  initial: off
  icon: mdi:flash
  
away_mode:
  name: Away mode
  initial: off
  icon: mdi:flash