####################################
#Configures what is/is not recorded#
####################################

include:
  entities:
    - sensor.date
    - sensor.ssl_cert_expiry

exclude:
  domains:
    - weblink
    - sensor