#####################################
#Connects HASS to the MQTT broker   #
#which is needed to use owntracks   #
#for presence detection and tracking#
#####################################

broker: !secret mqtt_broker
port: !secret mqtt_port
client_id: !secret mqtt_client_id
keepalive: 60
username: !secret mqtt_username
password: !secret mqtt_password