############################################
#Takes the selection from an input_select  #
#and converts this in to the scene selected#
############################################

alias: trigger_scene_master_bedroom_spring_blossom
trigger:
  platform: state
  entity_id: input_select.master_bedroom_scenes
  to: 'Spring Blossom'
action:
  service: script.turn_on
  entity_id: script.master_spring_blossom