########################
#Element of the package#
########################

- alias: "timer"
  trigger:
    platform: state
    entity_id: input_number.timer_minutes
  condition:
    - condition: template
      value_template: '{{ states.input_number.timer_minutes.state|float > 0}}'
  action:
    - service: script.turn_off
      entity_id: script.timer
    - service: script.turn_on
      entity_id: script.timer
      
- alias: "timer execute"
  trigger:
    platform: state
    entity_id: input_number.timer_minutes
  condition:
    - condition: template
      value_template: '{{ states.input_number.timer_minutes.state|float == 0.25}}'
  action:
    - service: notify.telegram_marc
      data:
        message: "The timer has expired - Home Assistant"
    - service: tts.google_say
      entity_id: media_player.ccagroup
      data:
        message: 'The timer has expired, The timer has expired'