########################
#Element of the package#
########################

masterbed_wake_up:
  sequence:
    - service: scene.turn_on
      entity_id: scene.master_bedroom_wake_up
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroomcca
        volume_level: '0.30'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroomcca
        media_content_id: !secret wakeup_track1
        media_content_type: 'audio/mp4'