########################
#Element of the package#
########################

- alias: 'Bedroom light on and play music'
  hide_entity: False
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.masterbed_alarm_clock_time_long.state }}'
  condition:
    condition: state
    entity_id: input_boolean.masterbed_alarm_clock_status
    state: 'on'
  action:
    - service: script.masterbed_wake_up
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.masterbed_alarm_clock_status

- alias: 'Bedroom clear boolean' 
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.bedroom_alarm_clock_time_long.state }}'
  condition:
    condition: state
    entity_id: input_boolean.bedroom_alarm_clock_repeat
    state: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bedroom_alarm_clock_status