########################
#Element of the package#
########################

masterbed_alarm_clock:
  name: 'Alarm Clock (MB)'
  entities:
    - input_boolean.masterbed_alarm_clock_status
    - sensor.masterbed_alarm_clock_time
    - input_slider.masterbed_alarm_clock_hour
    - input_slider.masterbed_alarm_clock_minute
    - input_boolean.masterbed_alarm_clock_repeat