########################
#Element of the package#
########################

masterbed_wake_up:
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroomccacca
        volume_level: '0.30'
    - service: media_player.play_media
      data_template:
        entity_id: media_player.bedroomcca
        media_content_id: !secret master_bedroom_wake_up_script
        media_content_type: 'audio/mp4'
#    - condition: or
#      conditions:
#        - condition: sun
#          before: sunrise
#          before_offset: '-00:40:00'
#        - condition: sun
#          after: sunset
#          after_offset: '-00:40:00'
#      state: 'home'
    - service: scene.turn_on
      entity_id: scene.master_bedroom_wake_up