##################################
#Hidden entities, setting icons  #
##################################

sensor.fibaro_system_fgd212_dimmer_2_heat_3_7:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_power_2_4:
  hidden: true
  
sensor.fibaro_system_fgd212_dimmer_2_power_2_8:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_power_3_4:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_power_3_8:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_power_management_2_11:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_power_management_3_11:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_sourcenodeid_2_2:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_sourcenodeid_3_2:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_system_2_12:
  hidden: true

sensor.fibaro_system_fgd212_dimmer_2_system_3_12:
  hidden: true