################################
#Hidden entities, setting icons#
#and adding friendly names     #
################################

light.master_bedroom:
  hidden: true

light.living_room:
  hidden: true

light.landing_g:
  hidden: true

light.bathroom_g:
  hidden: true