################################
#Hidden entities, setting icons#
#and adding friendly names     #
################################


#Sensors
sensor.ssl_cert_expiry:
  friendly_name: "SSL certificate expiry"
  icon: mdi:security-home

sensor.ha_upstream:
  friendly_name: "Upstream HA version"
  icon: mdi:cloud-sync

sensor.current_ha_version:
  icon: mdi:home-outline

#Trackers
device_tracker.phone_marcs_pixel_phone:
  hidden: true
  
group.marc_tracker:
  friendly_name: Marc
  entity_picture: /local/marc.jpg
  
group.laura_tracker:
  friendly_name: Laura
  entity_picture: /local/laura.jpg