################################
#Hidden entities, setting icons#
#and adding friendly names     #
################################

#Lights
light.boys_room_zwave_dimmer_level:
  friendly_name: Bedroom 2 Ceiling
  emulated_hue_name: "boys room light"
  
light.living_room_zwave_dimmer_level:
  friendly_name: Living Room Light
  emulated_hue_name: "living room light"
  
light.master_bedroom:
  hidden: true

#Switches
switch.hdmi_0:
  hidden: true

switch.hdmi_1:
  hidden: true

#Sensors
sensor.ssl_cert_expiry:
  friendly_name: "SSL certificate expiry"
  icon: mdi:security-home

sensor.ha_upstream:
  friendly_name: "Upstream HA version"
  icon: mdi:cloud-sync

sensor.installed_ha_version:
  icon: mdi:home-outline

#Trackers
device_tracker.phone_marcs_pixel_phone:
  hidden: true

#Calendar
sensor.calendar:
  icon: mdi:calendar-text