################################
#Hidden entities, setting icons#
#and adding friendly names     #
################################

#Lights
light.master_bedroom:
  hidden: true

light.living_room:
  hidden: true

#Sensors
sensor.ssl_cert_expiry:
  friendly_name: "SSL certificate expiry"
  icon: mdi:security-home

sensor.ha_upstream:
  friendly_name: "Upstream HA version"
  icon: mdi:cloud-sync

sensor.installed_ha_version:
  icon: mdi:home-outline

sensor.calendar:
  icon: mdi:calendar-text

sensor.dark_outside:
  icon: mdi:theme-light-dark