##################################
#Friendly names, setting icons   #
##################################

script.romance:
  can_cancel: false
  icon: mdi:creation

script.lullaby:
  can_cancel: false
  icon: mdi:creation

script.sync_dropbox:
  icon: mdi:dropbox

script.upgrade_hass:
  icon: cloud-check

script.github_push:
  icon: github-circle

script.github_pull:
  icon: github-box