#############################
#Ordering the tabs in the UX#
#############################

group.livingroom:
  order: 0

group.kitchen:
  order: 1

group.master_bedroom:
  order: 2

group.boys_room:
  order: 3

group.girls_room:
  order: 4

group.media:
  order: 5

group.location:
  order: 6

group.tools:
  order: 7

group.information:
  order: 8

group.security:
  order: 9