#############################
#Ordering the tabs in the UX#
#############################

group.downstairs:
  order: 1

group.media:
  order: 2

group.master_bedroom:
  order: 3

group.boys_room:
  order: 4

group.girls_room:
  order: 5

group.tools:
  order: 6

group.information:
  order: 7

group.security:
  order: 8

group.settings:
  order: 9