#############################
#Ordering the tabs in the UX#
#############################

group.downstairs:
  order: 0

group.master_bedroom:
  order: 1

group.boys_room:
  order: 2

group.girls_room:
  order: 3

group.media:
  order: 4

group.location:
  order: 5

group.tools:
  order: 6

group.information:
  order: 7

group.security:
  order: 8

group.settings:
  order: 9

group.all_automations:
  hidden: false

group.all_scripts:
  hidden: false
  control: hidden