################################
#A one-touch scene controller  #
################################

name: Livingroom dim
entities:
  light.living_room_zwave_dimmer_level:
    state: on
    transition: 2
    brightness: 35