################################
#A one-touch scene controller  #
################################

name: Livingroom normal
entities:
  light.fibaro_system_fgd212_dimmer_2_level_11_0:
    state: on
    transition: 2
    brightness: 120