########################
#Element of the package#
########################

radio_station:
  name: 'Select Radio Station:'
  options:
    - Free Radio CW
    - Free Radio 80s
    - Absolute Radio
    - Absolute 80s
    - Absolute 90s
    - Heart
    - Heart 80s
    - Sleep Radio

chromecast_radio:
  name: 'Select Speakers:'
  options:
    - Living Room
    - Kitchen
    - Master Bedroom
    - Downstairs
    - Everywhere
  initial: Everywhere
  icon: mdi:speaker-wireless