#################################
#Alerts me when Guest Mode has  #
#been on for too long (possibly)#
#################################

guest_mode_alert:
  name: Guest Mode has been on for a long time
  done_message: Guest Mode de-activated
  entity_id: input_boolean.guest_mode
  repeat:
    - 240
    - 120
  skip_first: true
  notifiers:
   - telegram_marc