###########################
#Shell scripts that can be#
#run on the system from HA#
###########################

renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

upgrade_hass: /home/hass/.homeassistant/extras/bash_scripts/upgrade-hass.sh

sync_dropbox: /usr/bin/python /home/hass/extras/bash_scripts/dropbox_sync.py