#################################
#Placing entities on the card   #
#################################

master_bedroom_lights:
  name: Lights
  entities:
    - light.bedroom_ceiling
    - light.bedroom_stairs
    - input_select.master_bedroom_scenes

livingroom_lights:
  name: Lights
  entities:
    - light.living_room_left
    - light.living_room_right
    - input_select.living_room_scenes

other_lights:
  name: Lights
  control: hidden
  entities:
    - light.landing
    - light.bathroom

All hue:
  - light.all_hue_lights