#################################
#Placing entities on the card   #
#################################

Phone trackers:
  - device_tracker.marc_pixel
  - device_tracker.forthygpixel
  - device_tracker.lauras_phone_lauras_phone