#################################
#Placing entities on the card   #
#################################

System:
  - updater.updater
  - sensor.installed_ha_version
  - sensor.ha_upstream
  - sensor.ssl_cert_expiry
  - sensor.cpu_speed
  - sensor.cpu_used
  - sensor.disk_used_
  - sensor.last_boot
  - sensor.ram_used
  - sensor.since_last_boot
  - sensor.speedtest_download
  - sensor.speedtest_ping
  - sensor.speedtest_upload

Maintenance:
  - input_boolean.maintenance_mode