########################
#Element of the package#
########################

living_wake_up:
  sequence:
    - service: light.turn_on
      data: 
        entity_id: light.living_room_zwave_dimmer_level
        brightness: 255
        transition: 10
    - service: tts.google_say
      entity_id: media_player.everywhere_group
      data:
        message: 'Alarm, Alarm, Alarm'