########################
#Element of the package#
########################

- platform: template
  sensors:
    living_alarm_clock_hour:
      value_template: '{{ states.input_slider.living_alarm_clock_hour.state | int }}'
    living_alarm_clock_minute:
      value_template: '{{ states.input_slider.living_alarm_clock_minute.state | int }}'
    living_alarm_clock_time:
      value_template: >-
        {{ states.sensor.living_alarm_clock_hour.state }}:
        {%- if states.sensor.living_alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.living_alarm_clock_minute.state }}
    living_alarm_clock_time_long:
      value_template: >-
        {% if states.sensor.living_alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.living_alarm_clock_hour.state }}:
        {%- if states.sensor.living_alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.living_alarm_clock_minute.state }}