########################
#Element of the package#
########################

- alias: 'Livingroom light on gradually with alarm'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.living_alarm_clock_time_long.state }}'
  condition:
    condition: state
    entity_id: input_boolean.living_alarm_clock_status
    state: 'on'
  action:
    - service: script.living_wake_up
      
- alias: 'Livingroom clear boolean' 
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.living_alarm_clock_time_long.state }}'
  condition:
    condition: state
    entity_id: input_boolean.living_alarm_clock_repeat
    state: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.living_alarm_clock_status