########################
#Element of the package#
########################

boys_alarm_clock:
  name: 'Alarm Clock (B2)'
  entities:
    - input_boolean.boys_alarm_clock_status
    - sensor.boys_alarm_clock_time
    - input_slider.boys_alarm_clock_hour
    - input_slider.boys_alarm_clock_minute
    - input_boolean.boys_alarm_clock_repeat