########################
#Element of the package#
########################

boys_wake_up:
  sequence:
    - service: light.turn_on
      data: 
        entity_id: light.boys_room_zwave_dimmer_level
        brightness: 255
        transition: 10