########################
#Element of the package#
########################

- alias: 'Boys light on gradually with alarm'
  hide_entity: False
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.boys_alarm_clock_time_long.state }}'
  condition:
    condition: state
    entity_id: input_boolean.boys_alarm_clock_status
    state: 'on'
  action:
    - service: script.boys_wake_up
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.boys_alarm_clock_status
          
- alias: 'Boys room clear boolean' 
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.boys_alarm_clock_time_long.state }}'
  condition:
    condition: state
    entity_id: input_boolean.boys_alarm_clock_repeat
    state: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.boys_alarm_clock_status