#####################
#This is just a test#
######################

kodi_on_idle_test:
    name: Kodi Alert Test
    entity_id: media_player.living_room_kodi
    state: 'idle'
    repeat: 30
    can_acknowledge: True
    skip_first: True
    notifiers: pushbullet