#######################################
#Resets the input_selector to 'Select'#
#when the lights are switched off     #
#######################################

alias: reset_scene_selector
trigger:
  platform: state
  entity_id: light.boys_room_zwave_dimmer_level
  to: 'off'
action:
  service: input_select.select_option
  data:
    entity_id: input_select.bedroom_two_scenes
    option: Select